branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
  main:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: fantasy-football
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
